### ISSUE TITLE
Can't open uinput device

### ISSUE THREAD

**Issue by ghost** [Emanem/js2xbox#2]
Tested on two separate machines, both running Antergos Linux. On both machines I get the error, "Exception: Can't open uinput device".  This happens whether I connect my PlayStation 3 controller via USB or Bluetooth.

**Comment by Emanem** [comment]
Hi, that's really weird - can you check if file "/dev/uinput" does exist in your distribution?
If no, can you search for such file "uinput"? If yes, what are the permissions? Have you tried to run it with sudo?

**Comment by ghost** [comment]
Sorry for the extremely late reply. Real life got in the way for a while....
Running it with sudo solved the problem! I don't know why I didn't think of that myself.
However, I'm getting some different issues now, with control mapping I think, which are making games unplayable. Would you prefer I go into detail in this thread or open up a new issue?

**Comment by Emanem** [comment]
Maybe open a new thread?
